### ISSUE TITLE
LFS files

### ISSUE THREAD

**Issue by mtouzot** [Raphael-Boichot/GameboyPrinterPaperSimulation#9]
Hi, 
As I find your project interesting, I want to work on it by moving Matlab code to Python. 
However, the first thing I've done was to use [git lfs](https://git-lfs.github.com/) to store the zip and png files in order to  work easily with large files. But... my `git push` didn't work : 

```console
$ git push origin develop
batch response: @mtouzot can not upload new objects to public fork mtouzot/GameboyPrinterPaperSimulation
error: failed to push some refs to 'https://github.com/mtouzot/GameboyPrinterPaperSimulation.git'
```

It seems that I only can resolve this by asking you if you want to enable[LFS on you project as mentionned [here](https://github.com/git-lfs/git-lfs/issues/1449#issuecomment-239831273). As you've got many png images and a zip file, using this feature could be usefull.

Thanks

**Comment by Raphael-Boichot** [comment]
Hello. I will deal with that within the week.

Raphaël

**Comment by Raphael-Boichot** [comment]
OK, I dug a little and mess with Git lfs. Git lfs is used by companies hosting there own files on their own servers and wanting to place them in remote clouds. I do not see any way of doing this when the files are host by Github itself, which is the case here. The different commands of Git lfs do not apply in my case.

I think that the best solution is to open a branch on the project itself.

Raphaël

**Comment by mtouzot** [comment]
Thanks for your research !

You're right, the easiest way would be for me to start a new one and to quote you by refering to your project.
